server:
  port: 8081
  url: localhost
spring:
  application:
    name: Manager BFF
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 93006914061-2gj4hkeuerdibbpd2h1o6b1dc1a9aobr.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:8081/oauth2/callback/google
            scope: openid, profile, email

---
spring:
  config:
    activate:
      on-profile: "dev"
  cloud:
    gateway:
      routes:
        - id: api
          uri: http://localhost:8080
          predicates:
            - Path=/api/product/**
        - id: nextjs
          uri: http://localhost:3000
          predicates:
            - Path=/**
---