name: Cart Service CI
on:
  push:
    branches:
      - main
    paths:
      - "cart/**"
      - ".github/workflows/cart-ci.yaml"
  pull_request:
    branches: ["main"]
    paths:
      - "cart/**"
      - ".github/workflows/cart-ci.yml"

  workflow_dispatch:
    
jobs:
  Analyze-CodeQL:
    name: Analyze code with CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Check Security by CodeQL
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: "java"
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:java"

  Analyze-SonarCloud:
    needs: Analyze-CodeQL
    name: Analyze code with SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3.0.4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=tanhaok_Book-Store -f cart
  
  Build:
    needs: Analyze-SonarCloud
    runs-on: ubuntu-latest
    name: Build code
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run Maven Build Command
        run: mvn clean install -DskipTests -f cart

  Unit-Test:
    needs: Build
    runs-on: ubuntu-latest
    name: Test code
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run Maven Test Command
        run: mvn test -f cart
      - name: Unit Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Test For Cart Result
          path: "cart/**/surefire-report/*.xml"
          reporter: java-junit
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run Maven Build Command
        run: mvn clean install -DskipTests -f cart
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v3
        with:
          context: ./cart
          push: true
          tags: ghcr.io/tanhaok/bookstore-cart:latest
    