name: Manager Service CI
on:
  push:
    branches:
      - main
    paths:
      - "manager/**"
      - ".github/workflows/manager-ci.yaml"
  pull_request:
    branches: ["main"]
    paths:
      - "manager/**"
      - ".github/workflows/manager-ci.yaml"

  workflow_dispatch:
    
jobs:
  Analyze-CodeQL:
    name: Analyze code with CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Check Security by CodeQL
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: "javascript"
      - run: npm ci
        working-directory: manager
      - run: npm run build
        working-directory: manager
      - run: npm run lint
        working-directory: manager
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:java"

  Analyze-SonarCloud:
    needs: Analyze-CodeQL
    name: Analyze code with SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache SonarCloud packages
        uses: actions/cache@v3.0.4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - run: npm ci
        working-directory: manager
      - run: npm run build
        working-directory: manager
      - run: npm run lint
        working-directory: manager
      - name: Build and analyze
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: manager
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  Build:
    needs: Analyze-SonarCloud
    runs-on: ubuntu-latest
    name: Build code
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run CI Command
        run: npm ci
      - name: Run Build Command
        run: npm run build
# Will add unit test job later
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run CI Command
        run: npm ci
      - name: Run Build command
        run: npm run build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v3
        with:
          context: ./manager
          push: true
          tags: ghcr.io/tanhaok/bookstore-manager:latest
    